-- MySQL Script generated by MySQL Workbench
-- Wed Sep  2 15:39:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wed_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wed_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wed_project` DEFAULT CHARACTER SET utf8 ;
USE `wed_project` ;

-- -----------------------------------------------------
-- Table `wed_project`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wed_project`.`authors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `biography` VARCHAR(255) NULL,
  `avatar` VARCHAR(100) NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wed_project`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wed_project`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wed_project`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wed_project`.`posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  `image` VARCHAR(100) NULL,
  `author_id` INT UNSIGNED NOT NULL,
  `categorie_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_authors_idx` (`author_id` ASC),
  INDEX `fk_posts_categories1_idx` (`categorie_id` ASC),
  CONSTRAINT `fk_posts_authors`
    FOREIGN KEY (`author_id`)
    REFERENCES `wed_project`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_categories1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `wed_project`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wed_project`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wed_project`.`tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wed_project`.`subscribers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wed_project`.`subscribers` (
  `email` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wed_project`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wed_project`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wed_project`.`posts_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wed_project`.`posts_has_tags` (
  `post_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`post_id`, `tag_id`),
  INDEX `fk_posts_has_tags_tags1_idx` (`tag_id` ASC),
  INDEX `fk_posts_has_tags_posts1_idx` (`post_id` ASC),
  CONSTRAINT `fk_posts_has_tags_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `wed_project`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `wed_project`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
